export const diffs = [
  { echarts: "United States", who: "United States of American" },
  { echarts: "Russia", who: "Russia Federation" },
  { echarts: "Korea", who: "Republic of Korea" },
  { echarts: "Iran", who: "Iran (Islamic Republic of)" },
  { echarts: "Bolivia", who: "Bolivia (Plurinational State of)" },
  { echarts: "Dem. Rep. Congo", who: "Democratic Republic of the Congo" },
  { echarts: "S. Sudan", who: "South Sudan" },
  { echarts: "Central African Rep.", who: "Central African Republic" },
  { echarts: "United Kingdom", who: "The United Kingdom" },
  { echarts: "Côte d'Ivoire", who: "Côte d’Ivoire" },
];

export const countryNamesWHO = [
  "United States of America",
  "Russian Federation",
  "Republic of Korea",
  "Iran (Islamic Republic of)",
  "Bolivia (Plurinational State of)",
  "Democratic Republic of the Congo",
  "South Sudan",
  "Central African Republic",
  "The United Kingdom",
  "Côte d’Ivoire",
  "United Republic of Tanzania",
  "Venezuela (Bolivarian Republic of)",
];
export const countryNamesEcharts = [
  "United States",
  "Russia",
  "Korea",
  "Iran",
  "Bolivia",
  "Dem. Rep. Congo",
  "S. Sudan",
  "Central African Rep.",
  "United Kingdom",
  "Côte d'Ivoire",
  "Tanzania",
  "Venezuela",
];
